package org.x2vc.schema.evolution;

import java.util.UUID;
import java.util.function.Consumer;

import org.x2vc.processor.IHTMLDocumentContainer;

/**
 * This component uses the trace output generated by the XSLT processor to identify missing parts of the input document
 * schema.
 */
public interface ISchemaEvolver {

	/**
	 * Analyze a HTML document and check for potential missing schema elements.
	 *
	 * @param taskID            the ID of the task being executed
	 * @param htmlContainer     the document to analyze
	 * @param modifierCollector a sink to handle the modification requests issued by the evolver
	 */
	void analyzeDocument(UUID taskID, IHTMLDocumentContainer htmlContainer,
			Consumer<ISchemaModifier> modifierCollector);

}
