package org.x2vc.xml.document;

import org.x2vc.xml.request.IDocumentRequest;

/**
 * This component processes an XML document request and produces an XML document
 * container that contains a document and a corresponding descriptor. The
 * results are generated by executing the rules.
 */
public interface IDocumentGenerator {

	/**
	 * Generates a document from the request.
	 *
	 * @param request
	 * @return the generated document
	 */
	IXMLDocumentContainer generateDocument(IDocumentRequest request);

}
