package org.x2vc.processor;

/**
 * An event traced while the XSLT was being processed. Events are generated by
 * trace messages and mark certain points in the flow of execution (usually the
 * beginning of new blocks or the occurrence of branching instructions).
 */
public interface ITraceEvent extends ITraceMessage {

	/**
	 * @return the ID of the XSLT element that was processed
	 */
	int getTraceID();

	/**
	 * @return the name of the XSLT element that was processed
	 */
	String getElementName();
}
