/*-
 * #%L
 * x2vc - XSLT XSS Vulnerability Checker
 * %%
 * Copyright (C) 2023 x2vc authors and contributors
 * %%
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * #L%
 */
package org.x2vc.xml.request;


import org.x2vc.xml.value.IValueGenerator;

/**
 * Controls the way MIXED content is generated by the {@link IValueGenerator}.
 */
public enum MixedContentGenerationMode {

	/**
	 * Generate the full range of mixed content, including various HTML tags. This mode is used for XSS checks.
	 */
	FULL,

	/**
	 * Only generate text contents and omit the HTML tags. This mode is used during the schema evolution to avoid
	 * unnecessary schema elements from being generated.
	 */
	RESTRICTED

}
